#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

apps-$(CONFIG_MODULE_CAPDL_LOADER) += capdl-loader-experimental

capdl-loader-experimental-y = kernel_elf common libsel4 $(libc) libcpio libelf libsel4muslcsys libplatsupport libsel4platsupport libsel4simple libutils libsel4utils libsel4debug

ifdef CONFIG_KERNEL_STABLE
capdl-loader-experimental-y += libsel4simple-stable
else
capdl-loader-experimental-y += libsel4simple-default
endif

capdl-loader-experimental: $(capdl-loader-experimental-y)
