/*
 * Copyright 2014, NICTA
 *
 * This software may be distributed and modified according to the terms of
 * the BSD 2-Clause license. Note that NO WARRANTY is provided.
 * See "LICENSE_BSD2.txt" for details.
 *
 * @TAG(NICTA_BSD)
 */

#ifndef CAPDL_SPEC_H__
#define CAPDL_SPEC_H__

#include "capdl.h"

/* This global is generated by the CapDL tools from the .cdl spec. */
extern CDL_Model capdl_spec;

#endif
