/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#pragma once

#include "capdl.h"

/* This global is generated by the CapDL tools from the .cdl spec. */
extern CDL_Model capdl_spec;
